sudo: required
dist: trusty
language: python

python:
  - "2.7"
  
# command to install dependencies
install:
  - sudo add-apt-repository -y ppa:juju/stable
  - sudo apt update
  - sudo apt install -yt trusty-backports lxd
  - sudo apt install -y juju
  - pip install flake8
  - pip install -r requirements.txt

# command to run tests
script:
  - make lint
  - make test
